config/routes.rb
Rails.application.routes.draw do

  get "/", to: "welcome#app", constraints: lambda {
    |solicitud| !solicitud.session[:user_id].blank?
  }  

  get "/", to: "welcome#index"

  resources :my_apps, except: [:index, :show]

  # Con los namespace podemos trabajar tranquilament en otras versiones sin romper la incompatibilidad
  # de la API

  namespace :api, defaults: { format: "json" } do
  	namespace :v1 do
  		resources :users, only: [:create]
  		# para que haga esto con la ruta: /polls pero lo manejara el controlador my_polls
  		resources :polls, controller: "my_polls", except: [:new, :edit] do
  			resources :questions, except: [:new, :edit]
        resources :answers, only: [:update, :destroy, :create]
  		end
      match "*unmatched", via: [:options], to: "master_api#xhr_options_request"
  	end
  end
  
  get "/auth/:provider/callback", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
end

app/models/my_app.rb
class MyApp < ApplicationRecord
  belongs_to :user
  has_many :tokens
  validates :title, presence: true
  validates :user, presence: true
  validates :secret_key, uniqueness: true
  validates :app_id, uniqueness: true

  before_create :generate_app_id
  before_create :generate_secret_key

  def is_your_token?(token)
    # Se necesita cerrar en llaves ese query para que la consulta la haga en tokens y no en my_app 
    self.tokens.where(tokens: { id: token.id }).any?
  end

  def is_valid_origin?(domain)
    self.javascript_origins.split(",").include?(domain)
  end

  private
  	def generate_app_id
  		begin
  			self.app_id = SecureRandom.hex
  		end while MyApp.where(app_id: self.app_id).any?
  	end

  	def generate_secret_key
  		begin
  			self.secret_key = SecureRandom.hex
  		end while MyApp.where(secret_key: self.secret_key).any?
  	end
end

app/controllers/my_apps_controller.rb
class MyAppsController < ApplicationController
  before_action :set_my_app, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /my_apps/new
  def new
    @my_app = MyApp.new
  end

  # GET /my_apps/1/edit
  def edit
  end

  # POST /my_apps
  # POST /my_apps.json
  def create
    @my_app = current_user.my_apps.new(my_app_params)

    respond_to do |format|
      if @my_app.save
        format.html { redirect_to "/", notice: 'My app was successfully created.' }
        format.json { render :show, status: :created, location: @my_app }
      else
        format.html { render :new }
        format.json { render json: @my_app.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /my_apps/1
  # PATCH/PUT /my_apps/1.json
  def update
    respond_to do |format|
      if @my_app.update(my_app_params)
        format.html { redirect_to "/", notice: 'My app was successfully updated.' }
        format.json { render :show, status: :ok, location: @my_app }
      else
        format.html { render :edit }
        format.json { render json: @my_app.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /my_apps/1
  # DELETE /my_apps/1.json
  def destroy
    @my_app.destroy
    respond_to do |format|
      format.html { redirect_to "/", notice: 'My app was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_my_app
      @my_app = MyApp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def my_app_params
      params.require(:my_app).permit(:title, :javascript_origins)
    end
end

app/helpers/my_apps_helper.rb
module MyAppsHelper
end

app/views/my_apps/_form.html.erb
<%= form_with(model: my_app, local: true) do |form| %>
  <% if my_app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(my_app.errors.count, "error") %> prohibited this my_app from being saved:</h2>

      <ul>
      <% my_app.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :my_app_title %>
  </div>

  <div class="input-field">
    <%= form.label :javascript_origins %>
    <%= form.text_field :javascript_origins, id: :my_app_javascript_origins %>
    <p style="margin: 0; padding: 0px;font-size: 12px;" >Separa por comas los origenes desde los que mandaras peticiones con AJAX</p>
  </div>

  <div style="margin-top: 1.5em;">
    <%= form.submit "Enviar", class:"btn" %>
  </div>
<% end %>

app/views/my_apps/edit.html.erb
<h1>Editing My App</h1>

<%= render 'form', my_app: @my_app %>

<%= link_to 'Show', @my_app %> |
<%= link_to 'Back', "/" %>

app/views/my_apps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Apps</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th>App</th>
      <th>Javascript origins</th>
      <th>Secret key</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @my_apps.each do |my_app| %>
      <tr>
        <td><%= my_app.user %></td>
        <td><%= my_app.title %></td>
        <td><%= my_app.app_id %></td>
        <td><%= my_app.javascript_origins %></td>
        <td><%= my_app.secret_key %></td>
        <td><%= link_to 'Show', my_app %></td>
        <td><%= link_to 'Edit', edit_my_app_path(my_app) %></td>
        <td><%= link_to 'Destroy', my_app, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New My App', new_my_app_path %>

app/views/my_apps/new.html.erb
<h1>Crear nueva aplicacion</h1>

<%= render 'form', my_app: @my_app %>

app/views/my_apps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @my_app.user %>
</p>

<p>
  <strong>Title:</strong>
  <%= @my_app.title %>
</p>

<p>
  <strong>App:</strong>
  <%= @my_app.app_id %>
</p>

<p>
  <strong>Javascript origins:</strong>
  <%= @my_app.javascript_origins %>
</p>

<p>
  <strong>Secret key:</strong>
  <%= @my_app.secret_key %>
</p>

<%= link_to 'Edit', edit_my_app_path(@my_app) %> |
<%= link_to 'Back', my_apps_path %>